### ISSUE TITLE
cmp function does not get converted

### ISSUE THREAD

**Issue by jugmac00** [gocept/gocept.template_rewrite#7]
The tool converted

`-                        <option tal:repeat="items python:sorted(lp.items(), lambda a,b: cmp(a[1], b[1]))"`
into
`+                        <option tal:repeat="items python:sorted(list(lp.items()), lambda a,b: cmp(a[1], b[1]))"`

cmp is no longer available in Python 3.

This is probably an issue in the underlying lib2to3.

**Comment by icemac** [comment]
Yes it is a problem which is not fixed by lib2to3, so we cannot do anything about it here. But it should be documented.

**Comment by icemac** [comment]
Fixed by #13.
