### ISSUE TITLE
tool should not touch pure html

### ISSUE THREAD

**Issue by jugmac00** [gocept/gocept.template_rewrite#8]
The tool rewrote

`-        <td valign="top" align="right" width="20">`

into

`+        <td valign="top"align="top" width="20">`

**Comment by viktordick** [comment]
I have a patch for this, with which I have been working. For some time now I wanted to create a PR, but the tests are still broken. I will see what I can do in the coming week or so

**Comment by jugmac00** [comment]
@viktordick Thank you very much for your patch, and providing this tool as open source!

The reported problem is fixed. There remain some other "false positives", which I will report once I am back from holiday.
