### ISSUE TITLE
do not change permissions

### ISSUE THREAD

**Issue by jugmac00** [gocept/gocept.template_rewrite#9]
For a template file with no changes the tool changed the file permissions:

```
diff --git a/src/Products/BlissUserMeetingCenter/www/BlissUserMeetingCenter/default_head.pt b/src/Products/BlissUserMeetingCenter/www/BlissUserMeetingCenter/default_head.pt
old mode 100755
new mode 100644
```

**Comment by icemac** [comment]
PageTemplates do not need/have the executable bit set.

**Comment by icemac** [comment]
@jugmac00 Are you okay with not fixing this issue?

**Comment by jugmac00** [comment]
@icemac Thank you for getting back to me.

I agree that page templates do not need, maybe even must not have the executable bit set.

On the other hand I would not expect this tool to change files when there is no Py2/Py3 issue.

Currently, when I run the tool on my code base it is like (guessed numbers):
- 100 files changed
- 80 of them only because of file permissions
- 10 because of false positives
- 10 because there was an actual Py2 / Py3 issue

But this is certainly an issue with my code base.

As the issue is rather on the side of the code base I think it is ok to close this issue.
